![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [7]:
my_array = np.arange(0, 10)
my_array_impares = my_array[my_array%2!=0]
my_array_impares[::-1]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [16]:
my_array[8:6:-1] #Tambien es inverso el slicing

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [25]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [3]:
matriz = np.arange(1, 21).reshape(4, 5)
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
np.flip(matriz)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [4]:

matriz2 = matriz.reshape(5,4)
matriz2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [5]:
matriz2[::-1, ::-1] #inversa las filas e inversa las columnas

array([[20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [7]:
submatriz = matriz[:2, :2]
submatriz

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [96]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [107]:
submatriz2 = matriz[::2, ::2]
submatriz2

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [132]:
submatriz3 = matriz[0:3, ::-1] #filas, damos la vuelta con el ::-1
#submatriz3 = np.flip(submatriz3, axis=1)
submatriz3

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [9]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
loro = x[x=="Loro"]
loro

array(['Loro', 'Loro'], dtype='<U5')

In [11]:
loro2 = x[np.where(x=="Loro")]
loro2

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [66]:
my_secuencia = np.arange(1, 21)
my_secuencia.reshape(2, 5, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [12]:
matriz_invertida = matriz[::-1, ::-1]
matriz_invertida


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [13]:
array10 = np.zeros((10))
array10[3] = 1
array10.itemsize, array10.nbytes, array10.dtype

(8, 80, dtype('float64'))

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [74]:
vector = np.arange(10, 50)
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [141]:
vector2 = np.array([1,2,0,0,4,0])
vector2 = np.argwhere(vector2 !=0)
vector2

array([[0],
       [1],
       [4]], dtype=int64)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [87]:

aleatorio = np.random.randint(10000, size = (10,10))
print(aleatorio)
print(np.min(aleatorio))
print(np.max(aleatorio)


[[9681 7857 2817 9014 5674 1548 3739 5217  797 7808]
 [8663 7396  374 7397 7692 6533 1876 2581 9928 7067]
 [8953 5486  186 1240 6025 1524   49 1490 5574  405]
 [9213 2306  393 9784 1233 9744 3459 7292  889 3541]
 [1322 9846 3488 7781 4882 3230 9188 5292 9505 3887]
 [4564 6947 9431 3425 3621 7009 6844 8175 4430 2388]
 [1612  155 3964 5534 2585 4276  180 2565 1649 9432]
 [4226 9062 6181 4260 3590 5452 4040 6976 5854 6490]
 [8727 1274 5931 7199 6542 8928 5945 4869 4470 9739]
 [7085 4357 4557 1770 4139 4132  489 8729 9236 3543]]
49
9928


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [91]:
aleatorio2 = np.random.rand(30)
print(aleatorio2)
np.mean(aleatorio2)

[0.64136027 0.0520417  0.03618151 0.83370672 0.6407662  0.49136113
 0.9984144  0.46999113 0.47714985 0.08586348 0.3341643  0.15329788
 0.14929537 0.47683081 0.45460285 0.94049238 0.11141517 0.40586921
 0.34254959 0.19775304 0.6519898  0.84184502 0.80500817 0.27667313
 0.56905861 0.83223672 0.26754071 0.67820645 0.91244875 0.34305361]


0.4823722656505124

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [20]:
Array_cuadrado = np.full((5,5), 1)
Array_cuadrado

Array_cuadrado[1:4, 1:4] = 0
Array_cuadrado


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [169]:
matriz8x8 = np.arange(64).reshape(8, 8)  
matriz8x8 = np.where(matriz8x8 % 2 == 0, 0, 1)
matriz8x8


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [181]:
# Crear un arreglo unidimensional
A = np.array([0, 1])

# Usar la función tile para repetir el arreglo
reps = (8, 4)  # Número de repeticiones a lo largo de cada eje
resultado = np.tile(A, reps)

resultado


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [190]:
aleatorio5x5 = np.random.randint(100, size = (5,5))
media = np.mean(aleatorio5x5)
desviacion = np.std(aleatorio5x5)

normalizacion = (aleatorio5x5-media)/desviacion
normalizacion


array([[ 0.73220508, -0.53418735, -0.64931394,  0.19494768,  1.30783801],
       [ 0.15657216, -0.03530549, -1.91570637, -1.26332239, -0.68768947],
       [-1.6854532 ,  1.38458906, -1.99245743,  0.92408272,  0.19494768],
       [-0.95631817,  0.38682533,  0.73220508,  1.65321776, -0.49581183],
       [ 0.65545402,  0.15657216,  0.50195191,  1.15433589,  0.0798211 ]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [194]:
secuencia10 = np.arange(11)
secuencia10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [202]:
secuencia_modificada = secuencia10.copy()  # Creamos una copia para no modificar la secuencia original
secuencia_modificada[3:9] = -1
secuencia_modificada

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [212]:
nueva_secuencia = secuencia_modificada[secuencia_modificada != -1]
nueva_secuencia

array([ 0,  1,  2,  9, 10])